// Mostlane-branded EM / PAT certificate PDF — drawn vector-side on lib/pdf.js
// (never a screenshot). One builder serves both types via a column spec. Sleeker
// take on the old Tysoft EasyCert layout: navy header band + logo, paired
// Client / Installation cards, a contractor strip, extent + comments, then a
// paginated striped results table, and a signed declaration block. A4 portrait.
import { PdfDoc, textWidth, jpegInfo, toWinAnsi } from "./pdf.js";

const NAVY = [0, 0.204, 0.408];       // #003468
const INK = [0.13, 0.15, 0.18];
const MUTE = [0.42, 0.46, 0.52];
const LINE = [0.80, 0.84, 0.88];
const STRIPE = [0.955, 0.968, 0.980];
const HEADFILL = [0.90, 0.93, 0.96];

const PAGE_W = 595, PAGE_H = 842, M = 40;
const CONTENT_W = PAGE_W - M * 2;

// Column specs (label + relative weight). "No." is fixed narrow.
const COLS = {
  em: [
    { key: "no", label: "No.", w: 0.06, align: "c" },
    { key: "normal", label: "Lamp Normal", w: 0.15, align: "c" },
    { key: "led", label: "LED Visible", w: 0.14, align: "c" },
    { key: "emergency", label: "Lamp Emergency", w: 0.16, align: "c" },
    { key: "battery", label: "Battery (min)", w: 0.13, align: "c" },
    { key: "comments", label: "Comments", w: 0.36, align: "l" },
  ],
  pat: [
    { key: "no", label: "No.", w: 0.05, align: "c" },
    { key: "appliance", label: "Appliance", w: 0.22, align: "l" },
    { key: "location", label: "Location", w: 0.16, align: "l" },
    { key: "cls", label: "Class", w: 0.07, align: "c" },
    { key: "visual", label: "Visual", w: 0.09, align: "c" },
    { key: "earth", label: "Earth (ohm)", w: 0.09, align: "c" },
    { key: "insulation", label: "Insul. (Mohm)", w: 0.10, align: "c" },
    { key: "result", label: "Result", w: 0.09, align: "c" },
    { key: "comments", label: "Comments", w: 0.13, align: "l" },
  ],
};
const TITLES = {
  em: "EMERGENCY LIGHTING TEST CERTIFICATE",
  pat: "PORTABLE APPLIANCE TEST CERTIFICATE",
};

const S = v => toWinAnsi(String(v == null ? "" : v));
function fit(str, size, maxW) {
  str = S(str);
  if (textWidth(str, size) <= maxW) return str;
  let s = str;
  while (s.length > 1 && textWidth(s + "…", size) > maxW) s = s.slice(0, -1);
  return s + "…";
}
function wrap(str, size, maxW, maxLines) {
  str = S(str);
  const words = str.split(/\s+/).filter(Boolean);
  const lines = []; let cur = "";
  for (const w of words) {
    const t = cur ? cur + " " + w : w;
    if (textWidth(t, size) <= maxW) { cur = t; continue; }
    if (cur) lines.push(cur);
    cur = w;
    while (textWidth(cur, size) > maxW && cur.length > 1) {   // hard-break a long word
      let c = cur; while (c.length > 1 && textWidth(c, size) > maxW) c = c.slice(0, -1);
      lines.push(c); cur = cur.slice(c.length);
    }
    if (maxLines && lines.length >= maxLines) break;
  }
  if (cur && (!maxLines || lines.length < maxLines)) lines.push(cur);
  if (maxLines && lines.length > maxLines) { lines.length = maxLines; lines[maxLines - 1] = fit(lines[maxLines - 1], size, maxW - textWidth("…", size)) ; }
  return lines.length ? lines : [""];
}

function headerBand(doc, rec, meta, pageNo, pageCount) {
  const bandH = 74;
  doc.rect(0, 0, PAGE_W, bandH, { fill: NAVY });
  // logo (left)
  if (meta.logo) {
    try { const d = jpegInfo(meta.logo); const h = 34; doc.image(meta.logo, M, 20, h * (d.w / d.h), h); } catch {}
  }
  // title (right)
  const title = TITLES[rec.type] || "TEST CERTIFICATE";
  doc.text(PAGE_W - M, 34, title, { size: 13, bold: true, alignRight: true, color: [1, 1, 1] });
  const sub = [rec.certNumber ? "Certificate No. " + rec.certNumber : "", rec.status === "draft" ? "DRAFT" : ""].filter(Boolean).join("   ·   ");
  if (sub) doc.text(PAGE_W - M, 52, sub, { size: 9.5, alignRight: true, color: [0.82, 0.88, 0.95] });
  return bandH;
}

function card(doc, x, yTop, w, title, lines) {
  const padX = 10, titleH = 16, lineH = 12;
  const body = lines.filter(l => l != null);
  const h = titleH + 6 + body.length * lineH + 8;
  doc.rect(x, yTop, w, h, { fill: [1, 1, 1], stroke: LINE, lw: 0.7 });
  doc.rect(x, yTop, w, titleH, { fill: HEADFILL });
  doc.text(x + padX, yTop + 11.5, S(title), { size: 8, bold: true, color: NAVY });
  let y = yTop + titleH + 12;
  for (const l of body) {
    doc.text(x + padX, y, fit(l.t != null ? l.t : l, l.bold ? 9 : 8.5, w - padX * 2), { size: l.bold ? 9 : 8.5, bold: !!l.bold, color: l.mute ? MUTE : INK });
    y += lineH;
  }
  return h;
}

function footer(doc, pageNo, pageCount, rec) {
  const y = PAGE_H - 26;
  doc.hr(M, y - 8, PAGE_W - M, { grey: true });
  const note = rec.type === "em"
    ? "Tested to BS 5266-1:2016. Generated by the Mostlane Portal."
    : "In-service inspection & testing to IET Code of Practice. Generated by the Mostlane Portal.";
  doc.text(M, y, note, { size: 7.5, color: MUTE });
  doc.text(PAGE_W - M, y, `Page ${pageNo} of ${pageCount}`, { size: 7.5, alignRight: true, color: MUTE });
}

// Pre-measure how many rows fit in a given table body height (fixed row height).
const ROW_H = 15, HEAD_H = 18;

export function buildCertPdf(record, meta = {}) {
  const rec = record || {};
  const type = rec.type === "pat" ? "pat" : "em";
  rec.type = type;
  const cols = COLS[type];
  const rows = Array.isArray(rec.rows) ? rec.rows : [];

  // Column x/width from weights.
  let cx = M;
  const layout = cols.map(c => { const w = CONTENT_W * c.w; const o = { ...c, x: cx, ww: w }; cx += w; return o; });

  // ── Work out ALL page breaks up front so footers carry the right total. Page 1
  // body starts under the intro block; later pages start just under the band.
  const laterTop = 74 + 14;
  const page1TableTop = laterTop + introHeight(rec) + 10;
  const bottomLimit = PAGE_H - 46;
  const page1Capacity = Math.max(0, Math.floor((bottomLimit - page1TableTop - HEAD_H) / ROW_H));
  const laterCapacity = Math.max(1, Math.floor((bottomLimit - laterTop - HEAD_H) / ROW_H));

  const pages = [];
  pages.push({ rows: rows.slice(0, page1Capacity), start: 0, tableTop: page1TableTop, intro: true });
  let i = page1Capacity;
  while (i < rows.length) {
    pages.push({ rows: rows.slice(i, i + laterCapacity), start: i, tableTop: laterTop, intro: false });
    i += laterCapacity;
  }

  // Declaration goes under the last table if ~120pt is free, else on its own page.
  const last = pages[pages.length - 1];
  const lastTableBottom = last.tableTop + HEAD_H + last.rows.length * ROW_H;
  const sigOwnPage = lastTableBottom + 130 > PAGE_H - 40;
  const totalPages = pages.length + (sigOwnPage ? 1 : 0);

  const doc = new PdfDoc(PAGE_W, PAGE_H);
  pages.forEach((pg, idx) => {
    if (idx > 0) doc.newPage(PAGE_W, PAGE_H);
    headerBand(doc, rec, meta, idx + 1, totalPages);
    if (pg.intro) drawIntro(doc, rec);
    else doc.text(M, laterTop - 2, (TITLES[type] || "") + " — continued", { size: 8, color: MUTE });
    drawTable(doc, layout, pg.rows, pg.start, pg.tableTop);
    footer(doc, idx + 1, totalPages, rec);
  });

  let sigY;
  if (sigOwnPage) {
    doc.newPage(PAGE_W, PAGE_H);
    headerBand(doc, rec, meta, totalPages, totalPages);
    footer(doc, totalPages, totalPages, rec);
    sigY = laterTop + 14;
  } else {
    sigY = lastTableBottom + 22;
  }
  drawDeclaration(doc, rec, meta, sigY);

  return doc.bytes();
}

function introHeight(rec) {
  // cards row height (max of the two) + contractor strip + extent + comments
  const cl = rec.client || {}, inst = rec.installation || {};
  const clLines = 1 + addrLines(cl).length;
  const inLines = 1 + addrLines(inst).length;
  const cardsH = 16 + 6 + Math.max(clLines, inLines) * 12 + 8;
  const conH = 40;
  const extentH = 14 + wrap(rec.extent || "", 8.5, CONTENT_W - 20, 3).length * 11 + 6;
  const commentsH = rec.comments ? (14 + wrap(rec.comments, 8, CONTENT_W - 20, 6).length * 10.5 + 6) : 0;
  return cardsH + 10 + conH + 10 + extentH + (commentsH ? 8 + commentsH : 0);
}
function addrLines(o) {
  o = o || {};
  const out = [];
  if (o.name) out.push({ t: o.name, bold: true });
  (o.address || "").split(/\s*,\s*/).filter(Boolean).forEach(a => out.push({ t: a }));
  if (o.postcode) out.push({ t: o.postcode });
  return out.length ? out : [{ t: "—", mute: true }];
}

function drawIntro(doc, rec) {
  const top = 74 + 14;
  const colW = (CONTENT_W - 12) / 2;
  const cl = rec.client || {}, inst = rec.installation || {}, con = rec.contractor || {};
  const h1 = card(doc, M, top, colW, "Client", addrLines(cl));
  const h2 = card(doc, M + colW + 12, top, colW, "Installation address", addrLines(inst));
  let y = top + Math.max(h1, h2) + 10;

  // Contractor strip
  const conLines = [
    { t: con.tradingTitle || "Mostlane", bold: true },
    { t: [con.address, con.postcode].filter(Boolean).join(", ") || "" },
    { t: [con.name ? "Tested by " + con.name : "", con.position].filter(Boolean).join(" · ") },
    { t: [con.telephone ? "Tel " + con.telephone : "", con.regNumber ? "Reg " + con.regNumber : "", con.date ? "Date " + con.date : ""].filter(Boolean).join("   ·   ") },
  ].filter(l => l.t);
  const conH = 16 + 6 + conLines.length * 12 + 8;
  doc.rect(M, y, CONTENT_W, conH, { fill: [1, 1, 1], stroke: LINE, lw: 0.7 });
  doc.rect(M, y, CONTENT_W, 16, { fill: HEADFILL });
  doc.text(M + 10, y + 11.5, "Contractor", { size: 8, bold: true, color: NAVY });
  let cy = y + 28;
  for (const l of conLines) { doc.text(M + 10, cy, fit(l.t, l.bold ? 9 : 8.5, CONTENT_W - 20), { size: l.bold ? 9 : 8.5, bold: !!l.bold, color: INK }); cy += 12; }
  y += conH + 10;

  // Extent
  doc.text(M, y, "Extent & limitations of the inspection and testing", { size: 8, bold: true, color: NAVY });
  y += 12;
  for (const ln of wrap(rec.extent || "—", 8.5, CONTENT_W, 3)) { doc.text(M, y, ln, { size: 8.5, color: INK }); y += 11; }
  y += 6;

  // Comments
  if (rec.comments) {
    doc.text(M, y, "Additional comments", { size: 8, bold: true, color: NAVY });
    y += 12;
    for (const ln of wrap(rec.comments, 8, CONTENT_W, 6)) { doc.text(M, y, ln, { size: 8, color: MUTE }); y += 10.5; }
  }
}

function drawTable(doc, layout, rows, startIndex, top) {
  // Header
  doc.rect(M, top, CONTENT_W, HEAD_H, { fill: NAVY });
  for (const c of layout) {
    const tx = c.align === "c" ? c.x + c.ww / 2 - textWidth(S(c.label), 8) / 2 : c.x + 6;
    doc.text(tx, top + 12.5, S(c.label), { size: 8, bold: true, color: [1, 1, 1] });
  }
  let y = top + HEAD_H;
  rows.forEach((r, k) => {
    if ((startIndex + k) % 2 === 1) doc.rect(M, y, CONTENT_W, ROW_H, { fill: STRIPE });
    for (const c of layout) {
      let v = r[c.key];
      if (c.key === "no") v = r.no != null ? r.no : (startIndex + k + 1);
      const size = 8;
      const txt = fit(v == null ? "" : v, size, c.ww - 10);
      const tx = c.align === "c" ? c.x + c.ww / 2 - textWidth(txt, size) / 2 : c.x + 6;
      const isFail = c.key === "result" && /fail/i.test(String(v || ""));
      doc.text(tx, y + 10.5, txt, { size, color: isFail ? [0.75, 0.10, 0.10] : INK, bold: isFail });
    }
    y += ROW_H;
  });
  // border
  doc.rect(M, top, CONTENT_W, HEAD_H + rows.length * ROW_H, { stroke: LINE, lw: 0.7 });
  // vertical rules
  for (const c of layout) if (c.x > M) doc.line(c.x, top, c.x, top + HEAD_H + rows.length * ROW_H, { stroke: LINE, lw: 0.5 });
}

function drawDeclaration(doc, rec, meta, y) {
  const con = rec.contractor || {};
  doc.hr(M, y, PAGE_W - M, { grey: true });
  y += 14;
  doc.text(M, y, "Declaration", { size: 9, bold: true, color: NAVY });
  y += 13;
  const decl = rec.declaration || (rec.type === "em"
    ? "I certify that the emergency lighting installation identified above has been inspected and tested to BS 5266-1:2016 and the results are as recorded."
    : "I certify that the portable appliances identified above have been inspected and tested and the results are as recorded.");
  for (const ln of wrap(decl, 8.5, CONTENT_W, 4)) { doc.text(M, y, ln, { size: 8.5, color: INK }); y += 11; }
  y += 10;
  // signature image
  if (meta.signature) {
    try { const d = jpegInfo(meta.signature); const h = 34; doc.image(meta.signature, M, y, Math.min(160, h * (d.w / d.h)), h); } catch {}
  }
  doc.line(M, y + 40, M + 180, y + 40, { stroke: LINE, lw: 0.6 });
  doc.text(M, y + 51, S([con.name, con.position].filter(Boolean).join("  ·  ") || "Engineer"), { size: 8.5, color: INK });
  doc.text(M, y + 62, "Signature & date: " + S(con.date || ""), { size: 7.5, color: MUTE });
}
